# Generated by Django 4.2.2 on 2023-07-11 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0002_remove_cliente_localidad_remove_cliente_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Localidades',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('contrasenia', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=30)),
                ('habilitado', models.BooleanField(default=False)),
                ('cuenta_activada', models.BooleanField(default=False)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_activacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50, unique=True)),
                ('calle', models.CharField(max_length=30)),
                ('altura', models.CharField(max_length=30)),
                ('sede_activa', models.BooleanField(default=False)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('comercio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.comercio')),
            ],
        ),
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField()),
                ('dni', models.CharField(max_length=8)),
                ('cuil', models.CharField(max_length=11)),
                ('estado', models.SmallIntegerField(default=0, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='web.usuario')),
            ],
            options={
                'verbose_name_plural': 'Repartidores',
            },
        ),
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuil', models.CharField(max_length=11)),
                ('comercio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.comercio')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='web.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='comercio',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='web.usuario'),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=30)),
                ('altura', models.CharField(max_length=30)),
                ('direccion', models.EmailField(max_length=50, unique=True)),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.localidad')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='web.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.CharField(max_length=30)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='web.usuario')),
            ],
            options={
                'verbose_name_plural': 'Administradores',
            },
        ),
    ]
