# Generated by Django 4.2.2 on 2023-07-13 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_pedido_producto_menu_pedidomenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ganancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_pago', models.DateField()),
                ('remuneracion', models.DecimalField(decimal_places=2, max_digits=9)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=7)),
                ('neto', models.DecimalField(decimal_places=2, max_digits=9)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='web.pedido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_retiro', models.DateTimeField()),
                ('fecha_entrega', models.DateTimeField()),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='web.pedido')),
            ],
        ),
        migrations.AddConstraint(
            model_name='entrega',
            constraint=models.UniqueConstraint(fields=('id', 'pedido'), name='unique_entrega_pedido'),
        ),
    ]
