# Generated by Django 4.2.2 on 2023-07-24 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_tipo_usuario_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='web.tipo'),
        ),
    ]
