from .usuarioAdmin import UsuarioAdmin
from .administradorAdmin import AdministradorAdmin
from .localidadAdmin import LocalidadAdmin
from .clienteAdmin import ClienteAdmin
from .repartidorAdmin import RepartidorAdmin
from .comercioAdmin import ComercioAdmin
from .sedeAdmin import SedeAdmin
from .gerenteAdmin import GerenteAdmin
from .productoAdmin import ProductoAdmin
from .menuAdmin import MenuAdmin
from .pedidoAdmin import PedidoAdmin
from .pedidomenuAdmin import PedidoMenuAdmin
from .ofertaAdmin import OfertaAdmin
from .entregaAdmin import EntregaAdmin
from .liquidacionAdmin import LiquidacionAdmin
from .gananciaAdmin import GananciaAdmin